### ISSUE TITLE
No need to wait after Wire.requestFrom() and no Wire.beginTransmission() or endTransmission() should be used with Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [jarzebski/Arduino-DS3231#17]
See: https://github.com/jarzebski/Arduino-INA219/issues/1
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.

**Comment by jarzebski** [comment]
will be fixed in next release
