### ISSUE TITLE
No need to send Wire.write(DS3231_REG_TIME) after setting a time again.

### ISSUE THREAD

**Issue by TzOk83** [jarzebski/Arduino-DS3231#20]
In the void `DS3231::setDateTime(uint16_t year, uint8_t month, uint8_t day, uint8_t hour, uint8_t minute, uint8_t second)` there are two points where the 0x00 address is being sent - on the beginning of the transmission (which is correct) and at the end of it (which is useless).

Lines 79 - 83 should be removed from DS3231.cpp.

**Comment by jarzebski** [comment]
will be fixed in release 1.1.0
