### ISSUE TITLE
clock.dateFormat() doesn't output anything in Arduino 1.8.7

### ISSUE THREAD

**Issue by tomjschwanke** [jarzebski/Arduino-DS3231#22]
After upgrading the Arduino IDE to 1.8.7 I only get blank output from clock.dateFormat(), even in the example sketch. Raw-output is still working (sketch DS3231_simple).

Once downgraded to 1.8.5 it's now working again.

1.8.7 complained about something in DS3231.cpp:
`DS3231.cpp:1064:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]`

**Comment by TomTomcrafter001** [comment]
Add: Happens on 1.8.5 too, if AVR Core is newer than 1.6.20

**Comment by erumaithi** [comment]
i am having the same issue ,  it seem the author have abandoned the library. this library have not been updated in 4 years.  it is a shame as it the best and the easiest.

**Comment by tomjschwanke** [comment]
> 
> 
> i am having the same issue , it seem the author have abandoned the library. this library have not been updated in 4 years. it is a shame as it the best and the easiest.

Yep, probably gonna start looking for a replacement soon, but I'll have to recode lots of my sketches *sigh*

**Comment by Ikar4n** [comment]
It was a simple fix.

[Arduino-DS3231-master.zip](https://github.com/jarzebski/Arduino-DS3231/files/2637387/Arduino-DS3231-master.zip)

**Comment by erumaithi** [comment]
thank you that is amaizing

**Comment by peiperakos** [comment]
Thanks its Works You save my day :)

**Comment by Eheran1** [comment]
Thanks!

**Comment by Jeins98** [comment]
With the newest Arduino IDE it didn't work. You have to downlaod Arduino IDE 1.8.5. It worked like a charm. For everyone who doesn't get it working.

**Comment by rwl7532** [comment]
> With the newest Arduino IDE it didn't work. You have to downlaod Arduino IDE 1.8.5. It worked like a charm. For everyone who doesn't get it working.

A few comments back is an updated zip file. It works with IDE 1.8.9

**Comment by FesSpinosa** [comment]
For me, the library works perfect on IDE 1.8.9(Windows Store 1.8.21.0). Where I can find a list which return values are possible? Many thanks.

**Comment by Jeins98** [comment]
> > With the newest Arduino IDE it didn't work. You have to downlaod Arduino IDE 1.8.5. It worked like a charm. For everyone who doesn't get it working.
> 
> A few comments back is an updated zip file. It works with IDE 1.8.9

Thanks, I will try it.

**Comment by FesSpinosa** [comment]
Got the list!!

**Comment by iBrick** [comment]
> 1.8.7 complained about something in DS3231.cpp:
> `DS3231.cpp:1064:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]`

Regarding this warning you may use quick fix in DS3231.cpp file: 
change lines:
char *daysLong[]  = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
char *daysShort[] = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
char *monthLong[]  = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November
char *monthShort[] = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};

to 
const char *daysLong[]  = {"Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"};
const char *daysShort[] = {"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"};
const char *monthLong[]  = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};
	const char *monthShort[] = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};

**Comment by PeterPerry0** [comment]
> It was a simple fix.
> 
> [Arduino-DS3231-master.zip](https://github.com/jarzebski/Arduino-DS3231/files/2637387/Arduino-DS3231-master.zip)

hello sir, you can try maintaining this lovely library by hosting it and giving credit to the author, since he has stopped working on it

**Comment by jarzebski** [comment]
fill be fixed in 1.1.0 release
