### ISSUE TITLE
Weird problem when using the library for DS3231 to display time on SSD1306 OLED

### ISSUE THREAD

**Issue by dziubym** [jarzebski/Arduino-DS3231#30]
I connected both DS3231 and SSD1306 to I2C bus vie A4 andA5 on Arduino nano. I am able to initialize both in the code. I can display stuff on the display and I canread time into e.g. serial monitor.
This library has a cool funcion clock.dateFormat that make formiating time and date really easy.
But here is the problem.

When I try to call this function OLED display does not initialise with the message 
SSD1306 allocation failed

There was some issues reported in this forum with clock.dateFormat. There was a fix posted which I applied.
But the issue is still there
Any anyone help?

**Comment by samlow-jun** [comment]
@dziubym Do you use Adafruit Library for the Oled ssd1306 ?
If yes, they have the default code with the older address 0x3D, try to change to 0x3C address and check if the OLDE starts working.
Also, you can use examples Wire -> i2c_scranner (Then in the port monitor check the output, if they connected correctly you will see the correct address for the OLED, but ssd1306 usually with 0x3C default address) to locate connected devices addresses... Hope that helps you.
