### ISSUE TITLE
The Day Suffix function appends "nd" for the 12th day

### ISSUE THREAD

**Issue by max688182** [jarzebski/Arduino-DS3231#4]
Not my code, but this code could fix this issue.

char *DS3231::strDaySufix(uint8_t day)
{
    switch (day)
    {
        case 1:
        case 21:
        case 31:
            return "st";
        case 2:
        case 22:
            return "nd";
        case 3:
        case 23:
            return "rd";
        default:
            return "th";
    }
}

**Comment by jarzebski** [comment]
will be fixed in 1.1.0 release
